# Generated by Django 5.1.7 on 2025-03-23 07:34

import account.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'این نام کاربری قبلا ثبت شده است.'}, help_text='الزامی. 150 حرف یا کمتر. فقط حروف، اعداد و @/./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='نام کاربری')),
                ('email', models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است.'}, max_length=254, unique=True, verbose_name='آدرس ایمیل')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین آی پی ورود')),
                ('require_2fa', models.BooleanField(default=False, verbose_name='نیاز به احراز دو مرحله\u200cای')),
                ('otp_secret', models.CharField(blank=True, max_length=32, verbose_name='کلید OTP')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='توکن تایید ایمیل')),
                ('is_verified', models.BooleanField(default=False, help_text='آیا حساب کاربری توسط مدیریت تایید شده است؟', verbose_name='تایید شده')),
                ('is_staff', models.BooleanField(default=False, help_text='مشخص می کند که آیا کاربر می تواند به این سایت مدیریت وارد شود یا خیر.', verbose_name='وضعیت کارکنان')),
                ('is_active', models.BooleanField(default=True, help_text='مشخص می کند که آیا این کاربر باید به عنوان فعال در نظر گرفته شود.', verbose_name='فعال')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'این شماره موبایل قبلا ثبت شده است.'}, max_length=128, null=True, region='IR', unique=True, verbose_name='شماره موبایل')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[account.models.validate_national_code], verbose_name='کد ملی')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('avatar', models.ImageField(blank=True, help_text='تصویر مربعی با حداقل اندازه 200x200 پیکسل', null=True, upload_to='profiles/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='آدرس دقیق')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('role', models.CharField(choices=[('ADMN', 'ادمین'), ('PROF', 'استاد'), ('STUD', 'دانشجو'), ('EMPL', 'کارمند'), ('CUST', 'مشتری')], default='CUST', max_length=4, verbose_name='نقش کاربری')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='پذیرش شرایط')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پذیرش شرایط')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='مجوز بازاریابی')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['mobile'], name='account_use_mobile_6a0dc0_idx'), models.Index(fields=['email'], name='account_use_email_553b8f_idx'), models.Index(fields=['national_code'], name='account_use_nationa_6b1fe8_idx'), models.Index(fields=['is_deleted'], name='account_use_is_dele_3bea72_idx')],
            },
            managers=[
                ('objects', account.models.CustomUserManager()),
                ('deleted_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
