# Generated by Django 5.1.7 on 2025-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_university_alter_user_city_alter_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد نقش'),
        ),
    ]
