# Generated by Django 5.1.7 on 2025-04-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_roll_confirmed',
            field=models.BooleanField(default=False, verbose_name='نقش تایید شده است؟'),
        ),
    ]
