# Generated by Django 5.1.7 on 2025-04-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_roll_confirmed'),
        ('university', '0002_university_city_university_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_roll_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('student', 'دانشجو'), ('professor', 'استاد')], max_length=20, verbose_name='نقش')),
                ('code', models.CharField(max_length=64, verbose_name='کد نقش')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='درخواست در')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تایید در')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='university.university', verbose_name='دانشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضویت',
                'verbose_name_plural': 'عضویت\u200cها',
                'unique_together': {('user', 'university', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='users', through='account.Membership', to='university.university', verbose_name='دانشگاه\u200cها'),
        ),
    ]
