# Generated by Django 5.1.7 on 2025-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_is_roll_confirmed_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('student', 'دانشجو'), ('professor', 'استاد'), ('Employee', 'کارمند')], max_length=20, verbose_name='نقش'),
        ),
    ]
