# Generated by Django 5.1.7 on 2025-04-12 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_membership_role'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='برای مثال: خانه، محل کار', max_length=100, verbose_name='عنوان نشانی')),
                ('category', models.CharField(choices=[('home', 'خانه'), ('work', 'محل کار'), ('other', 'سایر')], default='home', max_length=10, verbose_name='دسته\u200cبندی')),
                ('address', models.TextField(help_text='خیابان، پلاک، واحد و ...', verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(help_text='کد پستی 10 رقمی', max_length=10, verbose_name='کد پستی')),
                ('telephone', models.CharField(help_text='شماره تماس برای این نشانی', max_length=20, verbose_name='تلفن')),
                ('active', models.BooleanField(default=False, verbose_name='نشانی پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iranian_cities.city', verbose_name='شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iranian_cities.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نشانی',
                'verbose_name_plural': 'نشانی\u200cها',
                'ordering': ['-active', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'active'], name='account_add_user_id_6bb2ea_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
