# Generated by Django 5.1.7 on 2025-04-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address'),
        ('university', '0002_university_city_university_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('admin', 'ادمین'), ('student', 'دانشجو'), ('professor', 'استاد'), ('Employee', 'کارمند')], default='customer', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='university',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='university.university', verbose_name='دانشگاه'),
        ),
    ]
