# Generated by Django 5.1.7 on 2025-05-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('admin', 'ادمین'), ('student', 'دانشجو'), ('professor', 'استاد'), ('Employee', 'کارمند'), ('OFFI', 'دبیر رفاهی واحد')], default='customer', max_length=20, verbose_name='نقش'),
        ),
    ]
