# Generated by Django 5.1.7 on 2025-03-23 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده/نشده')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='شناسه URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده/نشده')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='شناسه URL')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200cها',
                'indexes': [models.Index(fields=['slug'], name='product_pro_slug_9fef6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده/نشده')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان محصول')),
                ('main_image', models.ImageField(upload_to='products/main/%Y/%m/%d/', verbose_name='تصویر اصلی')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت قبلی')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد محصول (SKU)')),
                ('short_description', models.TextField(max_length=500, verbose_name='توضیحات کوتاه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='شناسه URL')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن (کیلوگرم)')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='ابعاد (طول×عرض×ارتفاع)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productbrand', verbose_name='برند')),
                ('categories', models.ManyToManyField(related_name='products', to='product.productcategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مقدار تخفیف')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداکثر تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('valid_to', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('products', models.ManyToManyField(blank=True, to='product.product', verbose_name='محصولات مرتبط')),
                ('categories', models.ManyToManyField(blank=True, to='product.productcategory', verbose_name='دسته\u200cبندی\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('alt_text', models.CharField(blank=True, max_length=125, verbose_name='متن جایگزین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده/نشده')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نقد')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('verified_purchase', models.BooleanField(default=False, verbose_name='خرید تایید شده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقد و بررسی',
                'verbose_name_plural': 'نقد و بررسی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(max_length=50, verbose_name='سایز')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='جنس')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='تغییر قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='کلید جلسه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید محصول',
                'verbose_name_plural': 'بازدیدهای محصول',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='product_pro_price_3acd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='product_pro_created_22b186_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_pro_sku_34f508_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['-timestamp'], name='product_pro_timesta_56705e_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'timestamp'], name='product_pro_product_b84f5b_idx'),
        ),
    ]
