# Generated by Django 5.1.7 on 2025-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_price_3acd1d_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'is_active'], name='product_pro_slug_ec502b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'is_active'], name='product_pro_price_e0e858_idx'),
        ),
    ]
