# Generated by Django 5.1.7 on 2025-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_pro_price_3acd1d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='کد محصول (SKU)'),
        ),
    ]
