# Generated by Django 5.1.7 on 2025-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True, verbose_name='کد محصول (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=300, unique=True, verbose_name='شناسه URL'),
        ),
    ]
