# Generated by Django 5.1.7 on 2025-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag'),
        ('product', '0007_product_description_product_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='home.tag', verbose_name='تگ\u200cها'),
        ),
    ]
