# Generated by Django 5.1.7 on 2025-04-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('university', '0002_university_city_university_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.university', verbose_name='دانشگاه'),
        ),
    ]
