# Generated by Django 5.1.7 on 2025-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_siteoption_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoption',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/logo/options', verbose_name='لوگو'),
        ),
    ]
