# Generated by Django 5.1.7 on 2025-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_siteoption_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoption',
            name='logo',
            field=models.FileField(blank=True, upload_to='images/logo/options', verbose_name='لوگو'),
        ),
    ]
