# Generated by Django 5.1.7 on 2025-03-30 06:04

import django.core.validators
import django_extensions.db.fields
import djrichtextfield.models
import university.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="نام باید با 'دانشگاه آزاد' شروع شود", max_length=200, unique=True, validators=[university.models.validate_university_name], verbose_name='نام دانشگاه')),
                ('established_date', models.DateField(db_index=True, verbose_name='تاریخ تأسیس')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='آدرس')),
                ('post_code', models.CharField(db_index=True, max_length=200, verbose_name='کد پستی')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل رسمی')),
                ('website', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='آدرس وبسایت')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('description', djrichtextfield.models.RichTextField(verbose_name='توضیحات کامل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
